# Generated by Django 4.2.4 on 2023-08-30 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRecord',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(max_length=6, verbose_name='start time')),
                ('end_time', models.DateTimeField(max_length=6, verbose_name='end time')),
                ('load_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='appointment time')),
                ('docker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docker', to=settings.AUTH_USER_MODEL)),
                ('operator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentStatus',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=128, null=True, verbose_name='patient feedback')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('role', models.IntegerField(choices=[(0, 'patient'), (1, 'docker')], default=0)),
                ('user_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseRecord',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('docker_feedback', models.CharField(max_length=4096, null=True, verbose_name='docker feedback')),
                ('patient_feedback', models.CharField(max_length=4096, null=True, verbose_name='patient feedback')),
                ('appoint_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appoint', to='appointment.appointmentrecord')),
            ],
        ),
        migrations.AddField(
            model_name='appointmentrecord',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='appointment.appointmentstatus'),
        ),
    ]
